server:
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: ${SSL_PASSWORD} # 환경 변수 참조
    key-store-type: PKCS12
spring:
  datasource:
    username: ${DATABASE_USERNAME} # 환경 변수 참조
    url: ${DATABASE_URL} # 환경 변수 참조
    password: ${DATABASE_PASSWORD} # 환경 변수 참조
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENTID} # 환경 변수 참조
            client-secret: ${GOOGLE_CLIENSECRET} # 환경 변수 참조
            redirect-uri: ${GOOGLE_REDIRECTURI} # 환경 변수 참조
            scope:
              - email
              - profile
logging:
  level:
    org:
      springframework:
        security: DEBUG
        web: DEBUG

cloud:
  aws:
    stack:
      auto: false
    region:
      static: ap-northeast-2
    credentials:
      accessKey: ${IMG_AWS_ACCESSKEY} # 환경 변수 참조
      secretKey: ${IMG_AWS_SECRETKEY} # 환경 변수 참조
    s3:
      bucket: aucisonbucket