spring:
  elasticsearch:
    uris: "http://localhost:9200"
#    username: elastic  # Elasticsearch 사용자 이름
#    password: abcd1234  # Elasticsearch 비밀번호
  jpa:
    database: mysql
    show-sql: 'true'
  profiles:
#    include: aws, google, https
    include: test


#  redis:
#    host: localhost
#    port: 6379
#  h2:
#    console:
#      enabled: true

server:
  port: 443


jwt:
  secret: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAKb/4snaHoUpcJJuEghayTVfy3w3EUg19ftxM524fbpFwZsF2YqHP1HlaDcAtLdvNSuQWHemq53+fyxnQCyAFiUCAwEAAQ==
  expiration: 3600000

logging:
  level:
    root: info

#server:
#  port: 9876
