security:
  oauth2:
    client:
      registration:
        google:
          clientId: ??API?????ID
          clientSecret: ??API?????Secret
          redirectUriTemplate: "{baseUrl}/oauth2/callback/{registrationId}"
          scope:
            - email
            - profile
