spring:
  jpa:
    database: mysql
    show-sql: 'true'
  profiles:
    include: aws, google
  redis:
    host: localhost
    port: 6379
  h2:
    console:
      enabled: true

server:
  port: 443
  servlet:
    session:
      timeout: 30
    ssl:
#      enabled: true
#      key-alias: ayostore
#      key-store: ayostore.pkcs12
#      key-store-password: '@ayotera@'
#      key-password: '@ayotera@'
#      trust-store: ayotrust.pkcs12
#      trust-store-password: '@ayotera@'

jwt:
  secret: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAKb/4snaHoUpcJJuEghayTVfy3w3EUg19ftxM524fbpFwZsF2YqHP1HlaDcAtLdvNSuQWHemq53+fyxnQCyAFiUCAwEAAQ==
  expiration: 3600000
