spring:
  jpa:
    database: mysql
    show-sql: 'true'
  profiles:
    include: aws, google, https
#  redis:
#    host: localhost
#    port: 6379
  h2:
    console:
      enabled: true

server:
  port: 443

jwt:
  secret: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAKb/4snaHoUpcJJuEghayTVfy3w3EUg19ftxM524fbpFwZsF2YqHP1HlaDcAtLdvNSuQWHemq53+fyxnQCyAFiUCAwEAAQ==
  expiration: 3600000