server:
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: aucison1234
    key-store-type: PKCS12
spring:
  datasource:
    username: admin
    url: jdbc:mysql://aucison-db.cwwa1obel4ek.ap-northeast-2.rds.amazonaws.com:3306/aucison?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    password: aucison1234
  jpa:
    database: mysql
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 76213274445-a48jff50a3frvb7s1urp6eog1ukdckj2.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: https://localhost:443/api/auth/google/callback
            scope:
              - email
              - profile


